version: '3.8'

services:
  # Development service
  sportsx-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    networks:
      - sportsx-network
    profiles:
      - dev

  # Production service
  sportsx-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
    networks:
      - sportsx-network
    profiles:
      - prod
    restart: unless-stopped

networks:
  sportsx-network:
    driver: bridge