version: '3.8'

services:
  # Development service
  sportsx-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - VITE_PORT=8080
    networks:
      - sportsx-network
    profiles:
      - dev

  # Production service
  sportsx-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    networks:
      - sportsx-network
    profiles:
      - prod
    restart: unless-stopped

networks:
  sportsx-network:
    driver: bridge