version: '3.8'

services:
  sportsx-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "6001:8080"
    volumes:
      # Mount source code for hot reload
      - .:/app
      # Prevent overwriting node_modules
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - VITE_PORT=8080
      - CHOKIDAR_USEPOLLING=true
    networks:
      - sportsx-dev-network
    restart: unless-stopped

networks:
  sportsx-dev-network:
    driver: bridge